---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  tasks:
  - name: Create a new transit gateway with options
    aws.ec2_transit_gateway:
      auto_associate: no
      auto_propagate: no
      dns_support: True
      description: "nonprod transit gateway"
      purge_tags: False
      state: "{{ state }}"
      region: "{{ region }}"
      tags:
        Name: prodTransitGateway

