---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  tasks:
  - name: create a new ec2 VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}4" 
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ region }}"
      # enable dns support 
      dns_support: yes
      # enable dns hostnames
      dns_hostnames: yes
      tenancy: default
      state: "{{ state }}"
    register: vpc
    
  - name: Set VPC ID in variable
    set_stats:
      data:
        vpc_id4: "{{ vpc.vpc.id }}"
  
  - name: associate subnet to the VPC
    ec2_vpc_subnet:
      region: "{{ region }}"
      vpc_id: "{{ vpc.vpc.id }}"
      state: "{{ state }}"
      cidr: "{{ subnet_cidr }}"
      map_public: yes
      resource_tags:
        Name: "{{ subnet_name }}"
  - name: create IGW
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
     region: "{{ region }}"
     tags:
       Name: "igw-{{ vpc_name }}4"
    register: igw        
    
  - name: Lookup route tables
    ec2_vpc_route_table_info:
      region: "{{ region }}"
      filters:
        vpc-id: "{{ vpc.vpc.id }}"
    register: vpc_route_tables

  - name: Setup route tables
    ec2_vpc_route_table:
      region: "{{ region }}"
      vpc_id: "{{ vpc.vpc.id }}"
      lookup: id
      purge_subnets: false
      route_table_id: "{{ vpc_route_tables.route_tables[0].id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
